### PR TITLE
Remove testnet label

### PR DESCRIPTION
**Pull request by zgrguric**

### CODE REVIEW

**Comment by zgrguric** [comment]
Forgot to change network_id

**Comment by tequdev** [comment]
Is this change appropriate?
network_id=1 should be called Ripple testnet chain or Ripple testnet, not Ripple chain.

If it networkid=0, then you should use a name such as XRP Ledger mainnet , not Ripple.

**Comment by zgrguric** [comment]
> Is this change appropriate? network_id=1 should be called Ripple testnet chain or Ripple testnet, not Ripple chain.
> 
> If it networkid=0, then you should use a name such as XRP Ledger mainnet , not Ripple.
Agree as I stated above, It should be rephrased.

**Comment by WietseWind** [comment]
Already changed right after this PR :) Thanks!

**Pull request merged**
